// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | TimeLineServiceAvantageSlice
  | CallServiceSlice
  | ContactCallSlice
  | UseProductSlice
  | SecurityFeatureSlice
  | FeatureOneSlice
  | BrandLogoSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * CTA Button field in *Settings → Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.navigation[].cta_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta_button: prismic.BooleanField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Primary content in *BrandLogo → Primary*
 */
export interface BrandLogoSliceDefaultPrimary {
  /**
   * Heading field in *BrandLogo → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_logo.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * BrandLogos field in *BrandLogo → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_logo.primary.brandlogos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  brandlogos: prismic.GroupField<Simplify<BrandLogoDocumentDataBrandlogosItem>>;
}

/**
 * Default variation for BrandLogo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandLogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandLogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BrandLogo*
 */
type BrandLogoSliceVariation = BrandLogoSliceDefault;

/**
 * BrandLogo Shared Slice
 *
 * - **API ID**: `brand_logo`
 * - **Description**: BrandLogo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandLogoSlice = prismic.SharedSlice<
  "brand_logo",
  BrandLogoSliceVariation
>;

/**
 * Primary content in *CallService → Primary*
 */
export interface CallServiceSliceDefaultPrimary {
  /**
   * Image service call field in *CallService → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_service.primary.image_service_call
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_service_call: prismic.ImageField<never>;

  /**
   * Title service call field in *CallService → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_service.primary.title_service_call
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_service_call: prismic.TitleField;

  /**
   * Paragraphe call field in *CallService → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_service.primary.paragraphe_service_call
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphe_service_call: prismic.RichTextField;

  /**
   * Link WhatsApp field in *CallService → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: call_service.primary.link_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  link_whatsapp: prismic.BooleanField;
}

/**
 * Default variation for CallService Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallServiceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallService*
 */
type CallServiceSliceVariation = CallServiceSliceDefault;

/**
 * CallService Shared Slice
 *
 * - **API ID**: `call_service`
 * - **Description**: CallService
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallServiceSlice = prismic.SharedSlice<
  "call_service",
  CallServiceSliceVariation
>;

/**
 * Primary content in *ContactCall → Primary*
 */
export interface ContactCallSliceDefaultPrimary {
  /**
   * Title call number field in *ContactCall → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_call.primary.title_call_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_call_number: prismic.TitleField;

  /**
   * Images call number field in *ContactCall → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_call.primary.images_call_number
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images_call_number: prismic.ImageField<never>;
}

/**
 * Default variation for ContactCall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactCallSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactCallSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactCall*
 */
type ContactCallSliceVariation = ContactCallSliceDefault;

/**
 * ContactCall Shared Slice
 *
 * - **API ID**: `contact_call`
 * - **Description**: ContactCall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactCallSlice = prismic.SharedSlice<
  "contact_call",
  ContactCallSliceVariation
>;

/**
 * Primary content in *FeatureOne → Primary*
 */
export interface FeatureOneSliceDefaultPrimary {
  /**
   * Title featureOne field in *FeatureOne → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_one.primary.title_featureone
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_featureone: prismic.TitleField;

  /**
   * Image featureOne field in *FeatureOne → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_one.primary.image_featureone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_featureone: prismic.ImageField<never>;

  /**
   * Description featureOne field in *FeatureOne → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_one.primary.description_featureone
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_featureone: prismic.RichTextField;

  /**
   * Feature detail field in *FeatureOne → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_one.primary.feature_detail[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  feature_detail: prismic.GroupField<
    Simplify<FeatureOneDocumentDataFeatureDetailItem>
  >;
}

/**
 * Default variation for FeatureOne Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureOneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureOneSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureOne*
 */
type FeatureOneSliceVariation = FeatureOneSliceDefault;

/**
 * FeatureOne Shared Slice
 *
 * - **API ID**: `feature_one`
 * - **Description**: FeatureOne
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureOneSlice = prismic.SharedSlice<
  "feature_one",
  FeatureOneSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * image hero field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image_hero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_hero: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *SecurityFeature → Primary*
 */
export interface SecurityFeatureSliceDefaultPrimary {
  /**
   * TitleSecurity field in *SecurityFeature → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: security_feature.primary.titlesecurity
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlesecurity: prismic.TitleField;

  /**
   * Description Security field in *SecurityFeature → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: security_feature.primary.description_security
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_security: prismic.RichTextField;

  /**
   * Image et titre 1 field in *SecurityFeature → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: security_feature.primary.image_et_titre[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  image_et_titre: prismic.GroupField<
    Simplify<SecurityFeatureDocumentDataImageEtTitreItem>
  >;
}

/**
 * Default variation for SecurityFeature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecurityFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecurityFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecurityFeature*
 */
type SecurityFeatureSliceVariation = SecurityFeatureSliceDefault;

/**
 * SecurityFeature Shared Slice
 *
 * - **API ID**: `security_feature`
 * - **Description**: SecurityFeature
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecurityFeatureSlice = prismic.SharedSlice<
  "security_feature",
  SecurityFeatureSliceVariation
>;

/**
 * Primary content in *TimeLineServiceAvantage → Primary*
 */
export interface TimeLineServiceAvantageSliceDefaultPrimary {
  /**
   * TimelineService field in *TimeLineServiceAvantage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_service_avantage.primary.timelineservice[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timelineservice: prismic.GroupField<
    Simplify<TimeLineServiceAvantageDocumentDataTimelineserviceItem>
  >;

  /**
   * TimelineService2 field in *TimeLineServiceAvantage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_service_avantage.primary.timelineservice2[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timelineservice2: prismic.GroupField<
    Simplify<TimeLineServiceAvantageDocumentDataTimelineservice2Item>
  >;

  /**
   * TimelineService 3 field in *TimeLineServiceAvantage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_service_avantage.primary.timelineservice_3[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timelineservice_3: prismic.GroupField<
    Simplify<TimeLineServiceAvantageDocumentDataTimelineservice3Item>
  >;

  /**
   * TimelineService4 field in *TimeLineServiceAvantage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_service_avantage.primary.timelineservice4[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timelineservice4: prismic.GroupField<
    Simplify<TimeLineServiceAvantageDocumentDataTimelineservice4Item>
  >;

  /**
   * TimelineService5 field in *TimeLineServiceAvantage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_service_avantage.primary.timelineservice5[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timelineservice5: prismic.GroupField<
    Simplify<TimeLineServiceAvantageDocumentDataTimelineservice5Item>
  >;

  /**
   * TimelineService6 field in *TimeLineServiceAvantage → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_service_avantage.primary.timelineservice6[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timelineservice6: prismic.GroupField<
    Simplify<TimeLineServiceAvantageDocumentDataTimelineservice6Item>
  >;
}

/**
 * Default variation for TimeLineServiceAvantage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineServiceAvantageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimeLineServiceAvantageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TimeLineServiceAvantage*
 */
type TimeLineServiceAvantageSliceVariation =
  TimeLineServiceAvantageSliceDefault;

/**
 * TimeLineServiceAvantage Shared Slice
 *
 * - **API ID**: `time_line_service_avantage`
 * - **Description**: TimeLineServiceAvantage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineServiceAvantageSlice = prismic.SharedSlice<
  "time_line_service_avantage",
  TimeLineServiceAvantageSliceVariation
>;

/**
 * Primary content in *UseProduct → Primary*
 */
export interface UseProductSliceDefaultPrimary {
  /**
   * Title collection product field in *UseProduct → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: use_product.primary.title_collection_product
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_collection_product: prismic.TitleField;

  /**
   * product detail field in *UseProduct → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: use_product.primary.image_product[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  image_product: prismic.GroupField<
    Simplify<UseProductDocumentDataImageProductItem>
  >;
}

/**
 * Default variation for UseProduct Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UseProductSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UseProductSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *UseProduct*
 */
type UseProductSliceVariation = UseProductSliceDefault;

/**
 * UseProduct Shared Slice
 *
 * - **API ID**: `use_product`
 * - **Description**: UseProduct
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UseProductSlice = prismic.SharedSlice<
  "use_product",
  UseProductSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      BrandLogoSlice,
      BrandLogoDocumentDataBrandlogosItem,
      BrandLogoSliceDefaultPrimary,
      BrandLogoSliceVariation,
      BrandLogoSliceDefault,
      CallServiceSlice,
      CallServiceSliceDefaultPrimary,
      CallServiceSliceVariation,
      CallServiceSliceDefault,
      ContactCallSlice,
      ContactCallSliceDefaultPrimary,
      ContactCallSliceVariation,
      ContactCallSliceDefault,
      FeatureOneSlice,
      FeatureOneDocumentDataFeatureDetailItem,
      FeatureOneSliceDefaultPrimary,
      FeatureOneSliceVariation,
      FeatureOneSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SecurityFeatureSlice,
      SecurityFeatureDocumentDataImageEtTitreItem,
      SecurityFeatureSliceDefaultPrimary,
      SecurityFeatureSliceVariation,
      SecurityFeatureSliceDefault,
      TimeLineServiceAvantageSlice,
      TimeLineServiceAvantageDocumentDataTimelineserviceItem,
      TimeLineServiceAvantageDocumentDataTimelineservice2Item,
      TimeLineServiceAvantageDocumentDataTimelineservice3Item,
      TimeLineServiceAvantageDocumentDataTimelineservice4Item,
      TimeLineServiceAvantageDocumentDataTimelineservice5Item,
      TimeLineServiceAvantageDocumentDataTimelineservice6Item,
      TimeLineServiceAvantageSliceDefaultPrimary,
      TimeLineServiceAvantageSliceVariation,
      TimeLineServiceAvantageSliceDefault,
      UseProductSlice,
      UseProductDocumentDataImageProductItem,
      UseProductSliceDefaultPrimary,
      UseProductSliceVariation,
      UseProductSliceDefault,
    };
  }
}
