// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  brand_logo: dynamic(() => import("./BrandLogo")),
  call_service: dynamic(() => import("./CallService")),
  contact_call: dynamic(() => import("./ContactCall")),
  feature_one: dynamic(() => import("./FeatureOne")),
  hero: dynamic(() => import("./Hero")),
  security_feature: dynamic(() => import("./SecurityFeature")),
  time_line_service_avantage: dynamic(
    () => import("./TimeLineServiceAvantage"),
  ),
  use_product: dynamic(() => import("./UseProduct")),
};
